
NTC_MAPPINGS = dict(
    AL=[
        ("AL", "GR", "day_ahead"),
        ("AL", "ME", "day_ahead"),
        ("AL", "RS", "ne"),
        ("AL", "XK", "day_ahead"),
    ],
    AT=[
        ("AT", "CH", "day_ahead"),
        ("AT", "CZ", "ne"),
        ("AT", "DE_AMPRION", "ne"),
        ("AT", "DE_TENNET", "ne"),
        ("AT", "DE_TRANSNET", "ne"),
        ("AT", "HU", "ne"),
        ("AT", "IT", "day_ahead"),
        ("AT", "SI", "ne"),
    ],
    BE=[
        ("BE", "DE_AMPRION", "ne"),
        ("BE", "FR", "ne"),
        ("BE", "LU", "ne"),
        ("BE", "NL", "day_ahead"),
        ("BE", "GB", "day_ahead"),
    ],
    BA=[
        ("BA", "HR", "day_ahead"),
        ("BA", "ME", "day_ahead"),
        ("BA", "RS", "day_ahead"),
    ],
    BG=[
        ("BG", "GR", "day_ahead"),
        ("BG", "MK", "day_ahead"),
        ("BG", "RO", "day_ahead"),
        ("BG", "RS", "day_ahead"),
        ("BG", "TR", "ne"),
    ],
    HR=[
        ("HR", "BA", "day_ahead"),
        ("HR", "HU", "ne"),
        ("HR", "RS", "day_ahead"),
        ("HR", "SI", "ne"),
    ],
    CZ=[
        ("CZ", "AT", "ne"),
        ("CZ", "DE_50HZ", "ne"),
        ("CZ", "DE_TENNET", "ne"),
        ("CZ", "PL", "ne"),
        ("CZ", "SK", "ne"),
        ("PL_CZ", "DE_50HZ", "ne"),
    ],
    DK=[
        ("DK_CA", "DE_50HZ", "day_ahead"),
        ("DK_CA", "DE_TENNET", "day_ahead"),
        ("DK_CA", "NL", "day_ahead"),
        ("DK_CA", "NO", "ne"),
        ("DK_CA", "SE", "ne"),
    ],
    EE=[
        ("EE", "FI", "ne"),
        ("EE", "LV", "ne"),
        ("EE", "RU", "ne"),
    ],
    FI=[
        ("FI", "EE", "ne"),
        ("FI", "NO", "ne"),
        ("FI", "RU", "ne"),
        ("FI", "SE", "ne"),
    ],
    FR=[
        ("FR", "BE", "ne"),
        ("FR", "CH", "day_ahead"),
        ("FR", "ES", "day_ahead"),
        ("FR", "IT", "day_ahead"),
        ("FR", "GB", "day_ahead")
    ],
    DE=[
        ("DE_50HZ", "CZ", "ne"),
        ("DE_50HZ", "DK_CA", "day_ahead"),
        ("DE_50HZ", "PL", "ne"),
        ("DE_50HZ", "PL_CZ",  "ne"),
        ("DE_AMPRION", "AT", "ne"),
        ("DE_AMPRION", "BE", "ne"),
        ("DE_AMPRION", "CH", "ne"),
        ("DE_AMPRION", "FR", "ne"),
        ("DE_AMPRION", "LU", "ne"),
        ("DE_AMPRION", "NL", "ne"),
        ("DE_TENNET", "AT", "ne"),
        ("DE_TENNET", "CZ", "ne"),
        ("DE_TENNET", "DK_CA", "day_ahead"),
        ("DE_TENNET", "NL", "ne"),
        ("DE_TENNET", "NO", "ne"),
        ("DE_TENNET", "SE", "ne"),
        ("DE_TRANSNET", "AT", "ne"),
        ("DE_TRANSNET", "CH", "ne"),
        ("DE_TRANSNET", "FR", "ne"),
    ],
    GR=[
        ("GR", "AL", "day_ahead"),
        ("GR", "BG", "day_ahead"),
        ("GR", "IT", "day_ahead"),
        ("GR", "MK", "day_ahead"),
        ("GR", "TR", "day_ahead"),
    ],
    HU=[
        ("HU", "AT", "ne"),
        ("HU", "HR", "ne"),
        ("HU", "RO", "ne"),
        ("HU", "RS", "day_ahead"),
        ("HU", "SI", "ne"),
        ("HU", "SK", "ne"),
        ("HU", "UA_BEI", "ne"),
        ("HU", "UA_IPS", "day_ahead"),
    ],
    IE=[
        ("IE", "GB_NIR", "ne"),
        ("IE", "GB", "day_ahead"),
    ],
    IT=[
        ("IT", "AT", "day_ahead"),
        ("IT", "CH", "day_ahead"),
        ("IT", "FR", "day_ahead"),
        ("IT", "GR", "day_ahead"),
        ("IT", "ME", "day_ahead"),
        ("IT", "MT", "ne"),
        ("IT", "SI", "day_ahead"),
    ],
    XK=[
        ("XK", "AL", "day_ahead"),
        ("XK", "ME", "day_ahead"),
        ("XK", "MK", "day_ahead"),
        ("XK", "RS", "day_ahead"),
    ],
    LV=[
        ("LV", "EE", "ne"),
        ("LV", "LT", "ne"),
        ("LV", "RU", "ne"),
    ],
    LT=[
        ("LT", "BY", "ne"),
        ("LT", "LV", "ne"),
        ("LT", "PL", "ne"),
        ("LT", "RU_KGD", "ne"),
        ("LT", "SE", "ne"),
    ],
    LU=[
        ("LU", "BE", "ne"),
        ("LU", "DE_AMPRION", "ne"),
    ],
    MT=[
        ("MT", "IT", "ne"),
    ],
    MD=[
        ("MD", "RO", "ne"),
        ("MD", "UA_IPS", "ne"),
    ],
    ME=[
        ("ME", "AL", "day_ahead"),
        ("ME", "BA", "day_ahead"),
        ("ME", "IT", "day_ahead"),
        ("ME", "RS", "day_ahead"),
        ("ME", "XK", "day_ahead"),
    ],
    NL=[
        ("NL", "BE", "day_ahead"),
        ("NL", "DE_AMPRION", "ne"),
        ("NL", "DE_TENNET", "ne"),
        ("NL", "DK_CA", "day_ahead"),
        ("NL", "NO", "day_ahead"),
        ("NL", "GB", "day_ahead"),
    ],
    MK=[
        ("MK", "BG", "day_ahead"),
        ("MK", "GR", "day_ahead"),
        ("MK", "RS", "day_ahead"),
        ("MK", "XK", "day_ahead"),
    ],
    NO=[
        ("NO", "DE_TENNET", "ne"),
        ("NO", "DK_CA", "ne"),
        ("NO", "FI", "ne"),
        ("NO", "NL", "day_ahead"),
        ("NO", "GB", "ne"),
        ("NO", "SE", "ne"),
    ],
    PL=[
        ("PL", "CZ", "ne"),
        ("PL", "DE_50HZ", "ne"),
        ("PL", "LT", "ne"),
        ("PL", "SE", "ne"),
        ("PL", "SK", "ne"),
        ("PL", "UA_DOBTPP", "ne"),
        ("PL", "UA_IPS", "ne"),
    ],
    PT=[
        ("PT", "ES", "day_ahead"),
    ],
    RO=[
        ("RO", "BG", "day_ahead"),
        ("RO", "HU", "ne"),
        ("RO", "MD", "day_ahead"),
        ("RO", "RS", "day_ahead"),
        ("RO", "UA_BEI", "ne"),
        ("RO", "UA_IPS", "day_ahead"),
    ],
    RS=[
        ("RS", "AL", "ne"),
        ("RS", "BA", "day_ahead"),
        ("RS", "BG", "day_ahead"),
        ("RS", "HR", "day_ahead"),
        ("RS", "HU", "day_ahead"),
        ("RS", "ME", "day_ahead"),
        ("RS", "MK", "day_ahead"),
        ("RS", "RO", "day_ahead"),
        ("RS", "XK", "day_ahead"),
    ],
    SK=[
        ("SK", "CZ", "ne"),
        ("SK", "HU", "ne"),
        ("SK", "PL", "ne"),
        ("SK", "UA_BEI", "ne"),
        ("SK", "UA_IPS", "ne"),
    ],
    SI=[
        ("SI", "AT", "ne"),
        ("SI", "HR", "ne"),
        ("SI", "HU", "ne"),
        ("SI", "IT", "day_ahead"),
    ],
    ES=[
        ("ES", "PT", "day_ahead"),
        ("ES", "FR", "day_ahead"),
    ],
    SE=[
        ("SE", "DE_TENNET", "ne"),
        ("SE", "DK_CA", "ne"),
        ("SE", "FI", "ne"),
        ("SE", "LT", "ne"),
        ("SE", "NO", "ne"),
        ("SE", "PL", "ne"),
    ],
    CH=[
        ("CH", "AT", "day_ahead"),
        ("CH", "DE_AMPRION", "ne"),
        ("CH", "DE_TRANSNET", "ne"),
        ("CH", "FR", "day_ahead"),
        ("CH", "IT", "day_ahead"),
    ],
    TR=[
        ("TR", "BG", "ne"),
        ("TR", "GE", "day_ahead"),
        ("TR", "GR", "day_ahead"),
    ],
    UA=[
        ("UA_BEI", "HU", "ne"),
        ("UA_BEI", "RO", "ne"),
        ("UA_BEI", "SK", "ne"),
        ("UA_DOBTPP", "PL", "ne"),
        ("UA_IPS", "BY", "ne"),
        ("UA_IPS", "HU", "day_ahead"),
        ("UA_IPS", "MD", "ne"),
        ("UA_IPS", "PL", "ne"),
        ("UA_IPS", "RO", "day_ahead"),
        ("UA_IPS", "RU", "ne"),
        ("UA_IPS", "SK", "ne"),
    ],
    UK=[
        ("GB_NIR", "IE", "ne"),
        ("GB_NIR", "GB", "day_ahead"),
        ("GB", "BE", "day_ahead"),
        ("GB", "FR", "day_ahead"),
        ("GB", "IE", "day_ahead"),
        ("GB", "NL", "day_ahead"),
        ("GB", "NO", "ne"),
    ],
)
