"""Changed biggest generator column on 'countries' table

Revision ID: 133eb81a53a2
Revises: 9994e1fcf69f
Create Date: 2023-07-17 16:32:39.765069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133eb81a53a2'
down_revision = '9994e1fcf69f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('biggest_gen_capacity', sa.Integer(), nullable=True))
    op.add_column('country', sa.Column('biggest_gen_name', sa.Text(), nullable=True))
    op.drop_column('country', 'biggest_generator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('biggest_generator', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('country', 'biggest_gen_name')
    op.drop_column('country', 'biggest_gen_capacity')
    # ### end Alembic commands ###
