"""Added ntc forecasts table

Revision ID: 9994e1fcf69f
Revises: f96b3115f4ab
Create Date: 2023-07-17 16:14:41.117796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9994e1fcf69f'
down_revision = 'f96b3115f4ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ntc_forecast',
    sa.Column('from_country_code', sa.String(length=4), nullable=False),
    sa.Column('to_country_code', sa.String(length=4), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(precision=53), nullable=True),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_country_code'], ['country.code'], ),
    sa.ForeignKeyConstraint(['to_country_code'], ['country.code'], ),
    sa.UniqueConstraint('from_country_code', 'to_country_code', 'timestamp_utc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ntc_forecast')
    # ### end Alembic commands ###
