"""Added recommender output status table

Revision ID: dacbb74b7d3e
Revises: b3badf2ba803
Create Date: 2024-03-13 18:26:26.417042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacbb74b7d3e'
down_revision = 'b3badf2ba803'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('output_report',
    sa.Column('country_code', sa.String(length=4), nullable=False),
    sa.Column('target_day', sa.Date(), nullable=False),
    sa.Column('valid_hours', sa.Integer(), nullable=False),
    sa.Column('null_hours', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['country.code'], ),
    sa.UniqueConstraint('country_code', 'target_day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('output_report')
    # ### end Alembic commands ###
